apiVersion: v1
kind: Service
metadata:
  name: heart-disease-service
  labels:
    app: heart-disease-predictor
spec:
  selector:
    app: heart-disease-predictor
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer